name: AGNI ARDHAYA INDONESIA
favicon: null
layout_spectrum: 0.265361970057711
typography_spectrum: 0.8490665734279901
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9484340329654515
  lightness: 0.8121110261417925
  saturation: 0.8275193797890097
  rhythmicContrast: 0.4016022786963731
purpose: []
